'use strict';
// Endpoint declarations. Validation schemas remain in docs/api_document/driver.
module.exports = [
  {
    method: 'get',
    path: '/api/v1/driver-applications',
    action: 'listDriverApplications',
    contract: 'openapi',
  },
  {
    method: 'patch',
    path: '/api/v1/drivers/me',
    action: 'updateAvailability',
    contract: 'openapi',
  },
  {
    method: 'post',
    path: '/api/v1/drivers/me/locations',
    action: 'updateOwnLocation',
    contract: 'openapi',
  },
  {
    method: 'get',
    path: '/api/v1/drivers',
    action: 'getNearbyDrivers',
    contract: 'openapi',
  },
  {
    method: 'patch',
    path: '/api/v1/driver-applications/:id',
    action: 'reviewDriverApplication',
    contract: 'openapi',
  },
  {
    method: 'patch',
    path: '/api/v1/drivers/:id',
    action: 'updateDriverSuspension',
    contract: 'openapi',
  },
  {
    method: 'get',
    path: '/api/v1/drivers/:id',
    action: 'getDriver',
    contract: 'openapi',
  },
  {
    method: 'post',
    path: '/api/v1/internal-driver-registrations',
    action: 'createDriverRegistration',
    contract: 'internal',
    callers: ['identity'],
  },
  {
    method: 'get',
    path: '/api/v1/internal-drivers',
    action: 'getNearbyDriversInternal',
    contract: 'internal',
    callers: ['booking'],
  },
  {
    method: 'get',
    path: '/api/v1/internal-driver-registrations/:registrationId',
    action: 'getDriverRegistration',
    contract: 'internal',
    callers: ['identity'],
  },
  {
    method: 'post',
    path: '/api/v1/internal-drivers/:id/reservations/confirmations',
    action: 'confirmReservation',
    contract: 'internal',
    callers: ['booking'],
  },
  {
    method: 'post',
    path: '/api/v1/internal-drivers/:id/reservations/releases',
    action: 'releaseReservation',
    contract: 'internal',
    callers: ['booking'],
  },
  {
    method: 'put',
    path: '/api/v1/internal-drivers/:id/reservations',
    action: 'reserveDriver',
    contract: 'internal',
    callers: ['booking'],
  },
  {
    method: 'get',
    path: '/api/v1/internal-drivers/:id/reservations',
    action: 'getReservation',
    contract: 'internal',
    callers: ['booking'],
  },
  {
    method: 'post',
    path: '/api/v1/internal-drivers/:id/locations',
    action: 'recordTripLocation',
    contract: 'internal',
    callers: ['trip'],
  },
  {
    method: 'get',
    path: '/api/v1/internal-drivers/:id/locations/latest',
    action: 'getDriverLocation',
    contract: 'internal',
    callers: ['trip'],
  },
];
